version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: store-manager
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306